<?php
$CMSConfig=[
    'Database'=>
        [
          'Server'=>'localhost',
          'User'=>'franchuk02@adm',
          'Password'=>'k99FiMj=}A{j3%sT',
          'Database'=>'id12498286_guitar_shop'
        ]
];